---

# +----------------------------------------------------+
# |                                                    |
# |    File is managed by terraform (initially).       |
# |    See sommerfeld-io/dev-envorinment-config repo   |
# |    for the "real" source.                          |
# |                                                    |
# |    However, feel free to update this file          |
# |    because changes won't be overwritten.           |
# |                                                    |
# +----------------------------------------------------+

tasks:
  - name: Install yamllint
    init: sudo apt-get install -y yamllint
  - name: Install jarvis
    init: curl https://raw.githubusercontent.com/sebastian-sommerfeld-io/jarvis/main/src/main/install.sh | bash -

vscode:
  extensions:
    - asciidoctor.asciidoctor-vscode
    - aaron-bond.better-comments
    - ms-azuretools.vscode-docker
    - hashicorp.terraform
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-python.python
    - rebornix.ruby
    - timonwong.shellcheck
    - wingrunr21.vscode-ruby
    - ms-python.python
    - jebbs.plantuml
    - vscjava.vscode-java-pack
    - cschleiden.vscode-github-actions
