---
ls:
  .adoc: kebab-case | SCREAMING_SNAKE_CASE
  .puml: kebab-case
  .md: kebab-case | SCREAMING_SNAKE_CASE

  .conf: kebab-case
  .go: snake_case
  .json: kebab-case
  .rb: kebab-case
  .tf: kebab-case
  .yml: kebab-case
  .yaml: kebab-case

  .sh: kebab-case

  .css: kebab-case
  .html: kebab-case
  .js: kebab-case

  Dockerfile: PascalCase
  Vagrantfile: PascalCase
  Jenkinsfile: PascalCase

  .env: lowercase
  .folderslintrc: lowercase
  .shellcheckrc: lowercase
  .gitignore: lowercase
  .gitkeep: lowercase

ignore:
  - .adoc-links.json
  - src/main/github-config/assets/linters/.adoc-links.json
  - .ls-lint.yml
  - src/main/github-config/assets/linters/.ls-lint.yml
  - .yamllint.yml
  - src/main/github-config/assets/linters/.yamllint.yml

  - .git
  - .idea
  - node_modules
  - .gitpod.yml
  - target
