---
name: CI

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches-ignore:
      - dependabot/**
  schedule:
    - cron: '0 3 * * 1' # https://crontab.guru/#0_2_*_*_1

permissions:
  contents: read

jobs:
  module-ci-lint:
    uses: sommerfeld-io/.github/.github/workflows/module-ci-lint.yml@main

  on-failure:
    runs-on: ubuntu-latest
    needs: ['module-ci-lint']
    if: failure()

    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
