---
name: "Housekeeping: Labels"

on:
  schedule:
    - cron: '0 1 * * *' # https://crontab.guru
  push:
    branches:
      - main
    paths:
      - .github/workflows/housekeeping-labels.yml

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  call-workflow:
    uses: sommerfeld-io/.github/.github/workflows/housekeeping-labels.yml@main

  on-failure:
    runs-on: ubuntu-latest
    needs: call-workflow
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
