---
name: "Housekeeping: Repository"

on:
  schedule:
    - cron: '30 0 * * *' # https://crontab.guru
  push:
    branches:
      - main
    paths:
      - src/main/github-config/*
      - .github/workflows/housekeeping-repo.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call-workflow:
    uses: sommerfeld-io/.github/.github/workflows/housekeeping-repo.yml@main

  on-failure:
    runs-on: ubuntu-latest
    needs: call-workflow
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
