---
name: "Housekeeping: Issues + PRs"

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - assigned

permissions:
  contents: read
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  call-workflow:
    uses: sommerfeld-io/.github/.github/workflows/housekeeping-issues.yml@main
    secrets:
      GH_TOKEN_REPO_AND_PROJECT: ${{ secrets.GH_TOKEN_REPO_AND_PROJECT }}

  on-failure:
    runs-on: ubuntu-latest
    needs: call-workflow
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
